# MAC entry example, mind the quotes, do not erase
# "11:22:33:44:55:66" = "sn1234567"
# keep this entry, it is the logger we us in our BLE range tool

# "F0:5E:CD:25:92:95" = "2508703"   # TDO
"D0:2E:AB:D9:30:66" = "1111111"     # DO2